spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#            client-secret: client-secret
#            scope: name, email
#            client-id: client-id
#            client-name: Naver
#        provider:
#          naver:
#            user-name-attribute: response
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            token-uri: https://nid.naver.com/oauth2.0/token

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

server:
  port: ${SERVER_PORT}

auth:
  admin_token: ${ADMIN_TOKEN}
  artist_token: ${ARTIST_TOKEN}
  entertainment_token: ${ENTERTAINMENT_TOKEN}


