spring:
  data:
    redis:
      host: ${REDIS_SERVER}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    application:
      name: FanTreeHouse
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: false
        use_sql_comments: true
    defer-datasource-initialization: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  batch:
    jdbc:
      initialize-schema: always
  profiles:
    include: jwt, aws #jwt.yml 불러오기
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration/sql
    sql-migration-suffixes: sql
    baseline-version: 1


jwt:
  secret:
    key: ${JWT_SECRET_KEY}

server:
  port: 8080

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

#logging:
#  pattern:
#    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
#    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
#  level:
#    com.example.log: debug
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      max-history: 7
#  file:
#    name: /var/log/server.log