spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
server:
  port: ${SERVER_PORT}