### 아티스트 회원가입
POST http://localhost:8080/users/invite/artist
Content-Type: application/json

{
  "id": "test1234",
  "name": "명수",
  "nickname": "GGDD2",
  "email": "test@email.com",
  "password": "test1234",
  "profileImage": "https://music.youtube.com/playlist?list=PLldFwXdHiTkn4oi2CgqK06Wy2qMmPsFDT",
  "admin": false,
  "adminToken": "",
  "artist": true,
  "artistToken": "acRos3knitterUp2eTt1ng5",
  "entertainment": false,
  "entertainmentToken": ""
}

### 아티스트  생성
POST http://localhost:8080/artist
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MTIzNCIsImF1dGgiOiJBUlRJU1QiLCJzdGF0dXMiOiJBQ1RJVkVfVVNFUiIsImV4cCI6MTcyMTk3MTk0MiwiaWF0IjoxNzIxOTcwMTQyfQ.UI6crZMGDoCltpnLXaKVe0yAhEZFhq16PNxAsIPpaKg
Content-Type: application/json

{
  "artistName": "Jerry",
  "artistProfilePicture": "asdklasjd123"
}

### 아티스트 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "id": "test1234",
  "password": "test1234"
}

> {%
    client.log(response.headers.valueOf("Authorization"));
    client.log(response.headers.valueOf("refreshToken"));
    client.global.set("Authorization", response.headers.valueOf("Authorization"));
    client.global.set("refreshToken", response.headers.valueOf("refreshToken"));
%}

