### 커뮤니티 피드 좋아요
POST http://localhost:8080/artist/seventeen/feeds/1/like
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImF1dGgiOiJVU0VSIiwic3RhdHVzIjoiQUNUSVZFX1VTRVIiLCJleHAiOjE3MjIzMzU2ODUsImlhdCI6MTcyMjMzMzg4NX0.3AoSHv2rUE-gPSGok-AHWOdTcX3B9SBFqdT3zzp19G0
### 커뮤니티 피드 좋아요 취소
DELETE http://localhost:8080/artist/2NE1/feeds/2/like
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDIiLCJhdXRoIjoiVVNFUiIsInN0YXR1cyI6IkFDVElWRV9VU0VSIiwiZXhwIjoxNzIyMTc3NDAyLCJpYXQiOjE3MjIxNzU2MDJ9.PUFrCIvCU8-ZIaVwC3Yp6A9VdcUaxnRCMdsKMQAQhK4

### 커뮤니티 피드 댓글 좋아요
POST http://localhost:8080/artist/2NE1/feeds/1/comments/1/like
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDIiLCJhdXRoIjoiVVNFUiIsInN0YXR1cyI6IkFDVElWRV9VU0VSIiwiZXhwIjoxNzIyMTc3MTMzLCJpYXQiOjE3MjIxNzUzMzN9.j5nJMCQKxchYZbIMIMLF69hHpAkdrBiasskMTvfIuGs

### 커뮤니티 피드 댓글 좋아요취소
DELETE http://localhost:8080/artist/2NE1/feeds/1/comments/1/like
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDIiLCJhdXRoIjoiVVNFUiIsInN0YXR1cyI6IkFDVElWRV9VU0VSIiwiZXhwIjoxNzIyMTc3MTMzLCJpYXQiOjE3MjIxNzUzMzN9.j5nJMCQKxchYZbIMIMLF69hHpAkdrBiasskMTvfIuGs
