### 변수 정의
@enterName = hybe
#@groupName = aespa
#@artistId = 4

### 엔터 계정 생성
POST http://localhost:8080/enter
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzbWVudGVyMSIsImF1dGgiOiJFTlRFUlRBSU5NRU5UIiwic3RhdHVzIjoiQUNUSVZFX1VTRVIiLCJleHAiOjE3MjIyNzQ5MTAsImlhdCI6MTcyMjI3MzExMH0.rpfOBeP_X7nUcdMbSg86B2tNcddvd1vH5NmRQ7udDjg
Content-Type: application/json

{
  "enterName": "hybe",
  "enterNumber": 12334678910,
  "enterLogo": "image"
}

### 엔터 계정 조회
GET http://localhost:8080/enter/{{enterName}}
Authorization: {{Authorization}}

### 엔터 계정 수정 (엔터 네임)
PATCH http://localhost:8080/enter/{{enterName}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "enterName": "SM"
}

### 엔터 계정 수정 (엔터 넘버)
PATCH http://localhost:8080/enter/{{enterName}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "enterNumber": 321234
}

### 엔터 계정 수정 (엔터 로고)
PATCH http://localhost:8080/enter/{{enterName}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "enterLogo": "image123"
}

### 엔터 계정 삭제
DELETE http://localhost:8080/enter/{{enterName}}
Authorization: {{Authorization}}


### 아티스트 그룹 생성
POST http://localhost:8080/entertainments/{{enterName}}
Authorization:  {{Authorization}}
Content-Type: application/json

{
  "groupName": "에스파",
  "artistProfilePicture": "https://github.com/FanTree-House/FanTree-Back/tree/dev",
  "groupInfo" : "두 줄 소개",
  "artistIds": []
}

### 특정 아티스트 그룹 조회
GET http://localhost:8080/entertainments/{{enterName}}/{{groupName}}

###아티스트 그룹 전체 조회
GET http://localhost:8080/entertainments/{{enterName}}/groupName

### 아티스트 그룹 수정
PATCH http://localhost:8080/entertainments/{{enterName}}/에스파형님들
Authorization: {{Authorization}}
Content-Type: application/json

{
  "groupName": "aespa",
  "groupInfo": "그럴 수 있지",
  "artistIds": []
}

### 특정 아티스트 탈퇴
DELETE http://localhost:8080/entertainments/{{enterName}}/{{groupName}}/artists/{{artistId}}
Authorization: {{Authorization}}

### 아티스트 그룹 삭제
DELETE http://localhost:8080/entertainments/{{enterName}}/{{groupName}}
Authorization: {{Authorization}}