### 변수 정의
@enterName = hybe
#@groupName = aespa
#@artistId = 4

### 엔터 계정 생성
POST http://localhost:8080/enter
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbnRlcjEiLCJhdXRoIjoiRU5URVJUQUlOTUVOVCIsInN0YXR1cyI6IkFDVElWRV9VU0VSIiwiZXhwIjoxNzIyNTEwNjUyLCJpYXQiOjE3MjI1MDg4NTJ9.yyOg-pYmQtUbdrK-CD4iU0Yl8jJqPTgWIqfHxh8sheg
Content-Type: application/json

{
  "enterName": "hybe",
  "enterNumber": 12334678910,
  "enterLogo": "image"
}

### 엔터 계정 조회
GET http://localhost:8080/enter/{{enterName}}
Authorization: {{Authorization}}

### 엔터 계정 수정 (엔터 네임)
PATCH http://localhost:8080/enter/{{enterName}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "enterName": "SM"
}

### 엔터 계정 수정 (엔터 넘버)
PATCH http://localhost:8080/enter/{{enterName}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "enterNumber": 321234
}

### 엔터 계정 수정 (엔터 로고)
PATCH http://localhost:8080/enter/{{enterName}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "enterLogo": "image123"
}

### 엔터 계정 삭제
DELETE http://localhost:8080/enter/{{enterName}}
Authorization: {{Authorization}}


### 아티스트 그룹 생성
POST http://localhost:8080/entertainments/{{enterName}}
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzbWVudGVyMSIsImF1dGgiOiJFTlRFUlRBSU5NRU5UIiwic3RhdHVzIjoiQUNUSVZFX1VTRVIiLCJleHAiOjE3MjIzMjA0MjYsImlhdCI6MTcyMjMxODYyNn0.ecn2DMfo-v3gdA3Fj8j7gJhzkQVH_u8NWA7NBQZ3H8w
Content-Type: application/json

{
  "groupName": "에스파",
  "artistProfilePicture": "https://github.com/FanTree-House/FanTree-Back/tree/dev",
  "groupInfo" : "두 줄 소개",
  "artistIds": []
}

### 특정 아티스트 그룹 조회 (멤버포함)
GET http://localhost:8080/entertainments/hybe/seventeen

###아티스트 그룹 전체 조회
GET http://localhost:8080/entertainments/{{enterName}}/groupName

### 아티스트 그룹 수정
PATCH http://localhost:8080/entertainments/{{enterName}}/에스파형님들
Authorization: {{Authorization}}
Content-Type: application/json

{
  "groupName": "aespa",
  "artistProfilePicture": "https://github.com/FanTree-House/FanTree-Back/tree/dev",
  "artistIds": [3,4]
}

### 특정 아티스트 탈퇴
DELETE http://localhost:8080/entertainments/{{enterName}}/{{groupName}}/artists/{{artistId}}
Authorization: {{Authorization}}

### 아티스트 그룹 삭제
DELETE http://localhost:8080/entertainments/{{enterName}}/{{groupName}}
Authorization: {{Authorization}}