### 구독하기 (Subscript)

POST http://localhost:8080/artistGroup/subscript/Mouse
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDIiLCJhdXRoIjoiVVNFUiIsInN0YXR1cyI6IkFDVElWRV9VU0VSIiwiZXhwIjoxNzIxOTcyMDA5LCJpYXQiOjE3MjE5NzAyMDl9.74yvhM-twZYBceFqjnCfvez1XqXisZlIiVD9mZ6IYcQ
Content-Type: application/json


### 구독해지하기 (Subscript)
DELETE http://localhost:8080/artistGroup/subscript/2NE1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDIiLCJhdXRoIjoiVVNFUiIsInN0YXR1cyI6IkFDVElWRV9VU0VSIiwiZXhwIjoxNzIxOTA4MzM1LCJpYXQiOjE3MjE5MDY1MzV9.MqW6iIYU0U62ZwsuALnJo6KJLAuWjPZfzZrcfzV_Dc4
Content-Type: application/json

### 구독한 아티스트그룹 전체보기

GET http://localhost:8080/artistGroup/subscript
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDIiLCJhdXRoIjoiVVNFUiIsInN0YXR1cyI6IkFDVElWRV9VU0VSIiwiZXhwIjoxNzIxOTgwMjQ5LCJpYXQiOjE3MjE5Nzg0NDl9.9EYeFiNhibLEau2mkzVA7tK-VYd5Tw2UAQj8hnAjgBI
Content-Type: application/json