### 구독하기 (Subscript)

POST http://localhost:8080/artistGroup/subscript/aespa
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMzEiLCJhdXRoIjoiVVNFUiIsInN0YXR1cyI6IkFDVElWRV9VU0VSIiwiZXhwIjoxNzIzNTI4NzcwLCJpYXQiOjE3MjM1MjY5NzB9.vcLe3IFJ7SLXhaoszvMztAFjeVMMT_bDKLkIfBelwVM
Content-Type: application/json


### 구독해지하기 (Subscript)
DELETE http://localhost:8080/artistGroup/subscript/2NE1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDEiLCJhdXRoIjoiVVNFUiIsInN0YXR1cyI6IkFDVElWRV9VU0VSIiwiZXhwIjoxNzIyMDYzNjE1LCJpYXQiOjE3MjIwNjE4MTV9.KvfQAkHFfrlDHJI9Y6NeWusQOhGrKi9IK6ODY-aPOr8
Content-Type: application/json

### 구독한 아티스트그룹 전체보기

GET http://localhost:8080/artistGroup/subscript
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMzEiLCJhdXRoIjoiVVNFUiIsInN0YXR1cyI6IkFDVElWRV9VU0VSIiwiZXhwIjoxNzIzNTI4NzcwLCJpYXQiOjE3MjM1MjY5NzB9.vcLe3IFJ7SLXhaoszvMztAFjeVMMT_bDKLkIfBelwVM
Content-Type: application/json